from collections.abc import Sequence
from typing import Protocol

from timothy.core._typedefs import Obj


class PipelineStorage(Protocol):
    def fetch_one(self, name: str) -> Obj: ...
    def fetch_many(self, *names: str) -> Sequence[Obj]: ...
    def store_one(self, name: str, obj: Obj) -> None: ...
    def store_many(self, **name_to_obj_map: Obj) -> None: ...
    def list_names(self) -> Sequence[str]: ...
