line-length = 100
indent-width = 4

target-version = "py312"

[lint]
select = ["ALL"]
ignore = ["S101", "ANN101", "ANN102", "TD002", "TD003", "FIX002"]

[lint.per-file-ignores]
"tests/*" = ["D", "ANN001", "ANN201", "ARG001", "B018"]
"timothy/examples/basic_math.py" = ["T201"]